permalink: date
paginate: 3
pygments: true

sharing :
  twitter :
    size :
    via :
    count :
  facebook :
    appid : 205602882797935 # FIXME HARD
    layout : button_count
    font :
    faces : false
    width : 90
  googleplus :
    size : medium
    width :
    annotation : bubble
  linkedin :
    counter : right
