permalink: date
paginate: 3

# Settings for sharing 
# Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
# Add a tweet button 		=> provider : tweet
# Add a like button 		=> provider : like (you also need a facebook appid)
# Add a plus one button 	=> provider : plusone
# Add a HN button 		=> provider : hn
# Add them all (i.e. hn + tweet + plusone + like) => provider : all
# Set 'provider' to the sharing provider you want to use.
# Set 'provider' to false to turn sharing off globally.
#
sharing :
  provider : all
  twitter :
    size :
    via :
    count :
  facebook :
    appid : 205602882797935 # FIXME HARD
    layout : button_count
    font :
    faces : false
    width : 90
  googleplus :
    size : medium
    width :
    annotation : bubble
  linkedin :
    counter : right
