encoding: UTF-8
permalink: date
paginate: 3
pygments: true
safe: true
lsi: false

sharing :
  twitter :
    size :
    via :
    count :
  facebook :
    appid : 205602882797935 # FIXME HARD
    layout : button_count
    font :
    faces : false
    width : 90
  googleplus :
    size : medium
    width :
    annotation : bubble
  linkedin :
    counter : right

authors:
  michael-sperber:
    name: Michael Sperber
    image: /author/michael-sperber.jpg
    href: "http://www.active-group.de/unternehmen/sperber.html"
    about: '<a href="http://www.active-group.de/unternehmen/sperber.html">Dr. Michael Sperber</a> ist CTO der <a href="http://www.active-group.de/">Active Group GmbH</a> und international anerkannter Spezialist für alle Aspekte der funktionalen Programmierung.'
  stefan-wehr:
    name: Stefan Wehr
    image: /author/stefan-wehr.jpg
    href: "http://www.factisresearch.com/company.html#swehr"
    about: '<a href="http://www.factisresearch.com/company.html#swehr">Dr. Stefan Wehr</a> entwirft und entwickelt bei der <a href="http://www.factisresearch.com">factis research GmbH</a> komplexe Anwendungen sowohl in klassischen als auch in funktionalen Sprachen. Er ist international anerkannter Spezialist für funktionale Programmierung.'
  david-frese:
    name: David Frese
    image: /author/david-frese.jpg
    href: "http://www.active-group.de/unternehmen/frese.html"
    about: '<a href="http://www.active-group.de/unternehmen/frese.html">David Frese</a> ist Softwarearchitekt bei der <a href="http://www.active-group.de/">Active Group GmbH</a>, Diplom Informatiker, und verfügt über langjährige Erfahrung in funktionaler aber auch klassischer Programmierung in großen Projekten der Industrie.'
  andreas-bernauer:
    name: Andreas Bernauer
    image: /author/andreas-bernauer.jpg
    href: "http://www.active-group.de/unternehmen/bernauer.html"
    about: '<a href="http://www.active-group.de/unternehmen/bernauer.html">Dr. Andreas Bernauer</a> ist Software-Architekt bei der <a href="http://www.active-group.de/">Active Group GmbH</a> und beschäftigt sich seit über 10 Jahren mit funktionaler Programmierung.'
  uwe-schmidt:
    name: Uwe Schmidt
    image: /author/uwe-schmidt.jpg
    href: "http://www.fh-wedel.de/~si/"
    about: '<a href="http://www.fh-wedel.de/~si/">Prof. Dr. Uwe Schmidt</a> lehrt an der <a href="http://www.fh-wedel.de">FH Wedel</a> im Fachbereich Informatik Programmiersprachen und Software-Entwicklung, unter anderem seit dem Jahr 2000 <em>Funktionale Programmierung mit Haskell</em> im Master-Studiengang für Informatik. Er ist Autor des bekannten Haskell Pakets <a href="http://www.fh-wedel.de/~si/HXmlToolbox/index.html">HXT</a>, eine standardkonforme und sehr umfangreiche Bibliothek zur XML-Verarbeitung.'
  alexander-thiemann:
    name: Alexander Thiemann
    image: /author/alexander-thiemann.jpg
    href: "http://www.factisresearch.com/company.html#nthiemann"
    about: '<a href="http://www.factisresearch.com/company.html#athiemann">Alexander Thiemann</a> entwirft und entwickelt bei der <a href="http://www.factisresearch.com">factis research GmbH</a> &uuml;berwiegend Webanwendungen.'
  niklas-baumstark:
    name: Niklas Baumstark
    href: "http://www.factisresearch.com/company.html#nbaumstark"
    about: '<a href="http://www.factisresearch.com/company.html#nbaumstark">Niklas Baumstark</a> entwickelt neben seinem Studium Software bei der <a href="http://www.factisresearch.com">factis research GmbH</a> im funktionalen Paradigma. Zu seinen Spezialgebieten zählen systemnahe Programmierung und Algorithmen.'
  joachim-breitner:
    name: Joachim Breitner
    image: /author/joachim-breitner.png
    href: "http://www.joachim-breitner.de/blog/"
    about: '<a href="http://www.joachim-breitner.de/">Joachim Breitner</a> ist Doktorand am Karlsruher Institut für Technologie und forscht zur Semantik von Bedarfsauswertung. Seit 6 Jahren programmiert er Haskell und engagiert sich in der Community, etwa als Mitglied des Haskell Core Library Committees.'
  johannes-weiss:
    name: Johannes Weiß
    image: /author/johannes-weiss.png
    href: "http://www.johannesweiss.eu/"
    about: '<a href="http://johannesweiss.eu/">Johannes Weiß</a> arbeitet bei <a href="http://www.bromium.com/">Bromium</a>, einem vielversprechendem IT-Sicherheits-Startup in Cambridge, UK. Seit längerer Zeit interessiert er sich unter anderem für funktionale Programmiersprachen, insbesondere Haskell.'
  ingo-wechsung:
    name: Ingo Wechsung
    href: "http://www.contexo.de/"
    about: 'Ingo Wechsung arbeitet als IT-Berater für die Firma contexo GmbH in Reutlingen.'
  torsten-grust:
    name: Torsten Grust
    image: /author/torsten-grust.png
    href: "http://db.inf.uni-tuebingen.de/team/grust/"
    about: '<a href="http://db.inf.uni-tuebingen.de/team/grust/">Torsten Grust</a> ist Professor für Datenbanksysteme an der Universität Tübingen. Torsten ist am glücklichsten, wenn er in seiner Forschung Ideen aus der Welt der Datenbanksysteme und der funktionalen Programmierung mischen kann.'
  helmut-dobretzberger:
    name: Helmut Dobretzberger
    image: /author/helmut-dobretzberger.jpg
    href: "http://www.active-group.de/unternehmen/dobretzberger.html"
    about: 'todo'
